fix: proxy failing to start with aiohttp 3.10 (#90)
Proxy was failing to start with the error below when using aiohttp 3.10.

```
Traceback (most recent call last):
  File "E:\Projects\autojimmy\proxy\mapproxy.py", line 325, in _serviceCallback
    requestHandler = proxy.RequestHandler(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\autojimmy\proxy\requesthandler.py", line 102, in __init__
    self._connector = aiohttp.TCPConnector(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GrooveStar\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 784, in __init__
    super().__init__(
  File "C:\Users\GrooveStar\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 234, in __init__
    loop = loop or asyncio.get_running_loop()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
An exception occurred while starting the proxy
  File "E:\Projects\autojimmy\jobs\startupjobs.py", line 33, in run
    self.executeJob()
    proxy.MapProxy.instance().start(
  File "E:\Projects\autojimmy\proxy\mapproxy.py", line 161, in start
    raise RuntimeError(f'Map proxy failed to start ({message[1]})')
RuntimeError: Map proxy failed to start (no running event loop)
```

The issue was triggered by [this aiohttp
PR](https://github.com/aio-libs/aiohttp/pull/8512) which changed
behaviour so that some classes must now be explicitly passed a loop at
construction if there isn't one currently running.